In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

sns.set_style("whitegrid")

In [4]:
survey = pd.read_csv("/Users/nitin/Desktop/ba_final2/eVehicle-adoption-analytics/data/processed/survey_clean.csv")
survey.head()

,country_of_residence,area_type,age_group,annual_income_range_(in_local_currency_equivalent)_please_refer_your_country's_avg._national_income,occupation,do_you_currently_own_a_vehicle,what_type_of_vehicle_do_you_currently_own,"if_you_own_an_ev,_mention_your_ev_brand","if_you_do_not_own_an_ev,_are_you_considering_buying_one_in_the_next_2–3_years",average_daily_driving_distance,...,would_declining_ev_sales_reduce_your_confidence_in_an_ev_company’s_future,ev_motivation_score,ev_barrier_score,factor_price,factor_range,factor_brand,factor_design,factor_charging,ev_adoption_score,ev_readiness_score
0,India,3,4.0,Above average national income,Business owner / Self-employed,1.0,Petrol / Diesel,none,1.0,3,...,1,1.0,4.430597,1,0,0,0,0,-3.428571,1.0
1,India,3,4.0,Above average national income,Salaried employee,1.0,Petrol / Diesel,none,1.0,2,...,5,NaN,4.681731,1,1,1,1,1,NaN,NaN
2,India,3,4.0,Above average national income,Business owner / Self-employed,1.0,Petrol / Diesel,none,0.5,1,...,1,NaN,1.000000,0,1,0,1,1,NaN,NaN
3,India,1,4.0,Above average national income,Salaried employee,1.0,Petrol / Diesel,none,1.0,3,...,3,NaN,3.398054,0,1,0,0,0,NaN,NaN
4,India,3,NaN,Prefer not to say,Retired,1.0,Petrol / Diesel,none,0.5,1,...,3,NaN,NaN,1,1,0,1,1,NaN,NaN

In [5]:
survey.info()
survey.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 41 columns):
 #   Column                                                                                               Non-Null Count  Dtype
---  ------                                                                                               --------------  -----
 0   country_of_residence                                                                                 325 non-null    object
 1   area_type                                                                                            325 non-null    int64
 2   age_group                                                                                            313 non-null    float64
 3   annual_income_range_(in_local_currency_equivalent)_please_refer_your_country's_avg._national_income  325 non-null    object
 4   occupation                                                                                           325 non-null    object
 5   do_you_currently_own_a_vehicle                                                                       325 non-null    float64
 6   what_type_of_vehicle_do_you_currently_own                                                            325 non-null    object
 7   if_you_own_an_ev,_mention_your_ev_brand                                                              325 non-null    object
 8   if_you_do_not_own_an_ev,_are_you_considering_buying_one_in_the_next_2–3_years                        325 non-null    float64
 9   average_daily_driving_distance                                                                       325 non-null    int64
 10  lower_running_cost                                                                                   179 non-null    float64
 11  environmental_benefits                                                                               187 non-null    float64
 12  government_incentives___subsidies                                                                    187 non-null    float64
 13  rising_fuel_prices                                                                                   186 non-null    float64
 14  advanced_technology_&_features                                                                       186 non-null    float64
 15  brand_reputation                                                                                     186 non-null    float64
 16  charging_convenience                                                                                 186 non-null    float64
 17  evs_are_too_expensive                                                                                303 non-null    float64
 18  charging_infrastructure_is_insufficient                                                              310 non-null    float64
 19  battery_replacement_cost_is_high                                                                     310 non-null    float64
 20  driving_range_is_inadequate                                                                          311 non-null    float64
 21  charging_time_is_too_long                                                                            313 non-null    float64
 22  ev_resale_value_is_uncertain                                                                         313 non-null    float64
 23  limited_service_centers                                                                              313 non-null    float64
 24  preferred_ev_price_range                                                                             151 non-null    float64
 25  minimum_acceptable_driving_range_per_charge                                                          325 non-null    int64
 26  important_factors_when_choosing_an_ev                                                                325 non-null    object
 27  have_you_ever_sold_or_considered_selling_an_ev                                                       230 non-null    float64
 28  primary_reason_for_resale___consideration                                                            325 non-null    object
 29  do_you_believe_evs_depreciate_faster_than_petrol_or_diesel_vehicles                                  325 non-null    int64
 30  does_strong_ev_sales_increase_your_trust_in_a_company                                                325 non-null    int64
 31  would_declining_ev_sales_reduce_your_confidence_in_an_ev_company’s_future                            325 non-null    int64
 32  ev_motivation_score                                                                                  187 non-null    float64
 33  ev_barrier_score                                                                                     313 non-null    float64
 34  factor_price                                                                                         325 non-null    int64
 35  factor_range                                                                                         325 non-null    int64
 36  factor_brand                                                                                         325 non-null    int64
 37  factor_design                                                                                        325 non-null    int64
 38  factor_charging                                                                                      325 non-null    int64
 39  ev_adoption_score                                                                                    179 non-null    float64
 40  ev_readiness_score                                                                                   179 non-null    float64
dtypes: float64(23), int64(11), object(7)
memory usage: 104.2+ KB

,area_type,age_group,do_you_currently_own_a_vehicle,"if_you_do_not_own_an_ev,_are_you_considering_buying_one_in_the_next_2–3_years",average_daily_driving_distance,lower_running_cost,environmental_benefits,government_incentives___subsidies,rising_fuel_prices,advanced_technology_&_features,...,would_declining_ev_sales_reduce_your_confidence_in_an_ev_company’s_future,ev_motivation_score,ev_barrier_score,factor_price,factor_range,factor_brand,factor_design,factor_charging,ev_adoption_score,ev_readiness_score
count,325.000000,313.000000,325.000000,325.000000,325.000000,179.000000,187.000000,187.000000,186.000000,186.000000,...,325.000000,187.000000,313.000000,325.000000,325.000000,325.000000,325.000000,325.000000,179.000000,179.000000
mean,2.440000,2.792332,0.910769,0.581538,2.024615,3.770950,3.631016,3.069519,3.951613,4.064516,...,3.563077,3.676860,3.624405,0.612308,0.760000,0.393846,0.547692,0.587692,-0.020218,1.089562
std,0.720254,1.131571,0.285516,0.368887,0.892014,1.169867,1.370857,1.379762,1.384401,1.325887,...,1.214568,1.021502,0.950222,0.487975,0.427742,0.489355,0.498488,0.493009,1.172642,0.272729
min,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.428571,1.000000
25%,2.000000,2.000000,1.000000,0.500000,1.000000,3.000000,3.000000,2.000000,3.000000,4.000000,...,3.000000,3.128101,2.991005,0.000000,1.000000,0.000000,0.000000,0.000000,-0.571429,1.000000
50%,3.000000,3.000000,1.000000,0.500000,2.000000,4.000000,4.000000,3.000000,5.000000,5.000000,...,4.000000,3.933620,3.776974,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000
75%,3.000000,4.000000,1.000000,1.000000,3.000000,5.000000,5.000000,4.000000,5.000000,5.000000,...,5.000000,4.381735,4.368545,1.000000,1.000000,1.000000,1.000000,1.000000,0.714286,1.000000
max,3.000000,4.000000,1.000000,1.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.857143,2.724152

In [6]:
numeric_features = survey.select_dtypes(include=['int64','float64'])
numeric_features = numeric_features.fillna(numeric_features.mean())

In [7]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_features)